### ISSUE TITLE
Discussion about using Ext JS with other frameworks

### ISSUE THREAD

**Issue by jacobg** [Journerist/gulp-extify#2]
Hi, I saw this gulp plugin, and I'm curious how you are using it, e.g. with a different application framework (MVC, etc); ES6, jQuery and/or Twitter Bootstrap, etc. I'd like to use Ext JS 6 components selectively in a more modern, open-source and responsive application, so I'm currently researching if such an approach will be successful and how to go about it. Your plugin looks potentially to be a great tool to accomplishing such a task.

**Comment by Journerist** [comment]
Hey Jacobg,

you can already use babel to transpile your code. Gulp perfectly fits my needs. Checkout aurelia or angular 2 to see some good ES 2016 features in action and to get an idea how gulp can be used. Gulp-Extify does fit your needs regarding dependencies and in combination with the extjs module loader it replaces jspm. 

I use gulp-extify to build my production ready js file. I was sick of using senchacmd that can do so many different things but in building you are very inflexible. I am very satisfied using it for my full stack:

1. linting
2. building
3. test mock generating
4. testing using the production concatenated file
5. minify
6. deploy

If you have suggestions regarding more gulp-extify features or a new extjs module feel free to create a feature request.

regards
