### ISSUE TITLE
No error on open/close brace count mismatch

### ISSUE THREAD

**Issue by magneze** [Journerist/gulp-extify#6]
If a file is parsed that has an issue with open/close brace count mismatch then it is silently skipped rather than producing an error and failing.

**Comment by Journerist** [comment]
Hey,

thanks for reporting in. I'll fix it asap. Also feel free to create a PR if you need a fix quickly.

**Comment by Journerist** [comment]
I guess there is no real need here. I won't fix optional things here. if you need it create a PR and I will review it. Feel free to reopen it again.
