### ISSUE TITLE
Regex not matching class names with underscore

### ISSUE THREAD

**Issue by Liptoon** [Journerist/gulp-extify#7]
Hi,
in our codebase class names with underscores are used. The regex to match class names only allow alphanumeric content, so the plugin is not working as intended.

To fix this it would only need simple changes in the regexes, but it's questionable whether this plugin should allow underscores (and possible more non alphanumeric chars).

Another option would be to allow custom configuration.

Regards
Lip (member of gasX ;))

**Comment by Journerist** [comment]
Hey,

I publish v0.4.0 in npm and also allowed underscores see https://github.com/Journerist/gulp-extify/commit/c91660b1ab6b923621ad74c5e27df15db012f655

Let me know if this works for you.

Greetings

**Comment by Liptoon** [comment]
Thank you for your fast reaction :)
I'll let you know, when it's tested.

**Comment by Journerist** [comment]
any bugs can be addressed to me, directly :trollface: , greetings to the Gas-X QA department.
